services:
  ts-yougile:
    image: tailscale/tailscale:latest
    container_name: ts-yougile
    hostname: yougile
    environment:
      - TS_AUTHKEY=${TS_KEY}
      - TS_SERVE_CONFIG=./ts-config/funnel.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:internet 
    volumes:
      - ./state:/var/lib/tailscale
      - ./ts-config:/ts-config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  app: 
    build:
      context: .
      args:
        VERSION: ${YG_VERISON}
        EDITOR: ${EDITOR}
    container_name: yougile-app
    network_mode: service:ts-yougile
    depends_on: 
      - ts-yougile
    volumes:
      - ./yougile-data/database:/yougile/database
      - ./yougile-data/user-data:/yougile/user-data
      - type: bind
        source: ./yougile-data/conf.json
        target: /yougile/conf.json
      - type: bind
        source: ./yougile-data/license.key
        target: /yougile/license-host.key
      - type: bind
        source: ./yougile-data/machine.key
        target: /yougile/machine-host.key
    restart: unless-stopped

